CSect   Symbol  Value   LENGTH  Flags:
--------------------------------------
COPY    000000  00001B
        BUFEND  001033          R
        BUFFER  000033          R
        CLOOP   000006          R
        ENDFIL  00001A          R
        EXIT    000021          R
        FIRST   000000          R
        INPUT   000028          R
        LENGTH  000030          R
        MAXLEN  001033          R
        RDREC   001033          R
        RETADR  00002D          R
        RLOOP   00000A          R
        WLOOP   000006          R
        WRREC   00002C          R

Literal Table 
Name  Operand   Address  Length:
--------------------------------
X05  05        006A     1
